warehouse:
  id: warehouse_01
  #data_root: /opt/amr/data/warehouses
  data_root: /home/zyr/code/amr_edge_cloud_platform/data
  map_name: warehouse_01.yaml
  map_version: V1.0.1


edge_server:
  url: http://127.0.0.1:8080

  # upload:
  #   map: /api/warehouse/map
  #   zone: /api/warehouse/zone
  #   station: /api/warehouse/station
  #   wall: /api/warehouse/wall